name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe what you'd like to see.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve? What use case do you have?
      placeholder: "I'm trying to ... but currently ..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature or behavior you'd like.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've considered.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of MTChat would this affect?
      options:
        - Backend (Rust API)
        - Vue SDK (@mtchat/vue)
        - PrimeVue wrapper (@mtchat/vue-primevue)
        - Docker / Deployment
        - Documentation
        - Other
    validations:
      required: true
